### PR TITLE
Add message time to live (timeout) method/property on publisher configuration

### PR DESCRIPTION
**Pull request by alana1**
Request to add message time to live (timeout) method/property on publisher configuration instead of per message.

### CODE REVIEW

**Comment by jonnii** [comment]
@alana1 something looks wrong with the PR

**Comment by alana1** [comment]
I can't seem to add a new PR without having to select a branch or fork from the list.

**Comment by jonnii** [comment]
you need to:

1. fork
2. create a branch on your fork
3. make the changes
4. create a PR.

**Comment by jonnii** [comment]
@alana1 did you work out how to do this?

**Comment by alana1** [comment]
Jonnii, please discard this PR.

**Pull request closed without merging**
