### PR TITLE
Threadsafe access to the underlying list in teh TrackableFactory via …

### PR DESCRIPTION
**Pull request by bieri**
…ReaderWriterLockSlim

### CODE REVIEW

**Comment by bieri** [comment]
@jonnii tested and it resolves the issue.

**Comment by jonnii** [comment]
There's potential for deadlocks here.

**Comment by jonnii** [comment]
@bieri let me have a stab.

**Comment by bieri** [comment]
@jonnii what did i miss?

**Comment by jonnii** [comment]
in dispose you enter a lock, which could cause untrack which opens a lock etc...

**Comment by jonnii** [comment]
Also i think this is overkill as there is no read contention as there are no reads to the collection, only writes.

**Pull request closed without merging**
