### PR TITLE
[Feature] dotnet core support

### PR DESCRIPTION
**Pull request by jonnii**
- [ ] do not ignore lock files
- [ ] add all targets for net46
- [ ] what to do about serialization strategy?

### CODE REVIEW

**Comment by jonnii** [comment]
@cocowalla do you think we should have the lock file checked in? my thinking is that it's probably a good idea considering we are likely pinned to specific versions of our dependencies.

**Comment by cocowalla** [comment]
I'm not sure it's needed, since it will be automatically generated on `dotnet restore`. Also, in `project.json`, I believe if you don't use an asterisk to denote a 'floating' version, it specifies an exact version number.

**Comment by jonnii** [comment]
@cocowalla but the question is do we care about transitive dependencies? If so we should probably check it in, I'm not sure we do, and maybe for libraries it makes more sense _not_ to check it in. Do you have any advice about how to get multiple projects to build when doing a single `dotnet build`? We probably need a new build script to go along with this.

**Comment by cocowalla** [comment]
The simplest way is to use wildcards. On the system I'm currently working on, we simply do this from the solution root folder:
`dotnet build */**/project.json`

**Comment by jonnii** [comment]
@cocowalla made some more progress.

**Comment by cocowalla** [comment]
:+1:  

I assume `NullMessageTypeFactory` is just a shim to allow the assembly to build?

**Comment by jonnii** [comment]
@cocowalla it is yes. I need to figure out what to do with the one that does code gen, might be a version we publish which is only for full .net... or maybe we wait until netcore 1.1 which i think might have more of that api range covered? or maybe we get rid of that feature entirely and make it an app concern.

**Comment by cocowalla** [comment]
I quite like the idea of just leaving it up to the serialiser. If we take a dependency on `Newtonsoft.Json` (which supports .NET Core) and use `JsonNetMessageSerializer` as the default message serializer, we can handle serialising/deserialising interfaces out-of-the-box.

**Comment by jonnii** [comment]
@cocowalla do you want to try the package that comes out of `dotnet pack`?

**Comment by jonnii** [comment]
@cocowalla i got most of the integration tests to pass.

**Comment by jonnii** [comment]
@cocowalla did you manage to give it a whirl?

**Comment by cocowalla** [comment]
@jonnii Sorry, I missed the notification before, but I've been testing it this morning with pub/sub - seems to work great!

**Comment by jonnii** [comment]
@cocowalla i'm going to merge this, going to try to push forward on a netcore version!

**Comment by robertcoltheart** [comment]
Closing this.

**Pull request closed without merging**
