### PR TITLE
[bugfix] Amend the Chinchilla.Serializers.Protobuf.nuspec to correctly set the…

### PR DESCRIPTION
**Pull request by bieri**
… title to Chinchilla.Serializers.Protobuf

### CODE REVIEW

**Comment by bieri** [comment]
@jonnii Can  you republish the beta package for the proto package?

**Comment by jonnii** [comment]
@bieri i'm back in the office tomorrow, will do it first thing.

**Comment by jonnii** [comment]
@bieri published pre-release packages. lmk how they are and i'll cut a real build

**Comment by jonnii** [comment]
@bieri package is here: https://www.nuget.org/packages/chinchilla.serializers.protobuf

**Pull request merged**
