### PR TITLE
Amend the TrackableFactory to use a ConcurrentDictionary under the co…

### PR DESCRIPTION
**Pull request by bieri**
…vers to prevent the Thread Access issues found in testing.

### CODE REVIEW

**Comment by bieri** [comment]
@jonnii I am not crazy about this implementation, and thought about using something other than GetHashCode() as the key to the ConcurrentDictionary, but it seemed to patch the issue that I was seeing.  I found a thread access violation during the remove process when executing ~200 RPC style requests per second.  I have a test harness that shows this, but it will take some time to translate it to something that is generic.

**Comment by jonnii** [comment]
I can see how the current code could cause an issue. Perhaps just use regular lock primitives to synchronize access to the list? ConcurrentDictionary seems a little heavy handed. If you want to go that route it might be easier to add a `string Key` property on every trackable, but we'd have to make sure that it's something reasonable for each type that implements it.

**Comment by bieri** [comment]
I don't think a string property will work, I was firing off approximately
400 request of the same TTrackable type, so it has to be indexed by
something object specific rather than '''typeof(TTrackable)''' . I chose
ConcurrentDictionary as it just seemed safer than locking primitives tbh

**Comment by bieri** [comment]
@jonnii here is an alternative using primitives. I have yet to test, but let me know which one you prefer.

**Comment by bieri** [comment]
ersion,

**Pull request closed without merging**
